[package]
name = "plain_bitassets_app_rpc_api"
authors.workspace = true
edition.workspace = true
version.workspace = true

[dependencies]
bip300301.workspace = true
fraction = { version = "0.14.0", features = ["with-serde-support"] }
jsonrpsee = { version = "0.20.0", features = ["macros"] }
plain_bitassets = { path = "../lib" }

[lib]
name = "plain_bitassets_app_rpc_api"
path = "lib.rs"